### ISSUE TITLE
Unable to use "from lab_coffee_utils import load_coffee_data"

### ISSUE THREAD

**Issue by Prazhar** [jxareas/Machine-Learning-Notebooks#1]
How to fix this error "ModuleNotFoundError: No module named 'lab_coffee_utils'"?

**Comment by jxareas** [comment]
`lab_coffee_utils` is just a helper file that defines functions and utilities for visualizing and analyzing a coffee roasting data set using TensorFlow and Matplotlib. [You can check it here.](https://github.com/jxareas/Machine-Learning-Notebooks/blob/master/2_Advanced_Learning_Algorithms/Week%201.%20Neural%20Networks/lab_coffee_utils.py)

 To address your error, ensure that the `lab_coffee_utils` file is located in the correct directory. The code expects it to be in the same location as the notebooks. If the file is already in the correct location, try restarting your Jupyter kernel or the notebook server to refresh the module imports.

Feel free to reach out if you have any further questions.

**Comment by Prazhar** [comment]
Thanks
